<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
        <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
        <LangVersion>latest</LangVersion>
        <OutputType>WinExe</OutputType>
        <RootNamespace>AITool</RootNamespace>
        <AssemblyName>AITool</AssemblyName>
        <Deterministic>false</Deterministic>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <UseVSHostingProcess>true</UseVSHostingProcess>
        <CodeAnalysisRuleSet>UI.ruleset</CodeAnalysisRuleSet>
        <RunCodeAnalysis>false</RunCodeAnalysis>
        <ShouldCreateLogs>True</ShouldCreateLogs>
        <AdvancedSettingsExpanded>False</AdvancedSettingsExpanded>
        <UpdateAssemblyVersion>True</UpdateAssemblyVersion>
        <UpdateAssemblyFileVersion>True</UpdateAssemblyFileVersion>
        <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
        <AssemblyVersionSettings>None.None.Increment.DeltaDayStamp</AssemblyVersionSettings>
        <UpdatePackageVersion>False</UpdatePackageVersion>
        <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
        <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
        <AssemblyFileVersionSettings>None.None.Increment.DeltaDayStamp</AssemblyFileVersionSettings>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
        <LangVersion>latest</LangVersion>
        <CodeAnalysisRuleSet>UI.ruleset</CodeAnalysisRuleSet>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationIcon>Logo_old.ico</ApplicationIcon>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    </PropertyGroup>
    <PropertyGroup>
        <StartupObject>AITool.Program</StartupObject>
    </PropertyGroup>
    <ItemGroup>
        <Compile Update="CheckedComboBox.cs">
            <SubType>Component</SubType>
        </Compile>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Settings.Designer.cs">
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
        </Compile>
        <None Include="..\.editorconfig">
            <Link>.editorconfig</Link>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Content Include="TestImage.jpg">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="TestVehicleImage.jpg">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="sqlite3.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Logo_old.ico" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Installer\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Angle" Version="3.6.1" />
        <PackageReference Include="AWSSDK.Rekognition" Version="4.0.100.14" />
        <PackageReference Include="Markdig" Version="1.4.0" />
        <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
        <PackageReference Include="NAudio.Vorbis" Version="3.0.0" />
        <PackageReference Include="NAudio.Wasapi" Version="3.1.0" />
        <PackageReference Include="NAudio.WinForms" Version="3.1.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="NLog" Version="6.2.1" />
        <PackageReference Include="NVorbis" Version="0.10.5" />
        <PackageReference Include="Octokit" Version="14.0.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="4.1.2" />
        <PackageReference Include="SolarCalculator" Version="3.6.1" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
        <PackageReference Include="System.Management" Version="10.0.0" />
        <PackageReference Include="System.Speech" Version="10.0.0" />
        <PackageReference Include="Telegram.Bot" Version="22.10.3.1" />
        <PackageReference Include="WindowsAPICodePack" Version="8.0.15.2" />
        <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="ObjectListView.Repack.NET6Plus" Version="2.9.5" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <None Update="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <None Update="tick.wav">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>